In [1]:
import pandas as pd

In [2]:
df_raw_test_1 = pd.read_csv('./raw_dataset/Test_case_1.csv')

C:\Users\Khalid\AppData\Local\Temp\ipykernel_1688\2106927555.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw_test_1 = pd.read_csv('./raw_dataset/Test_case_1.csv')

In [3]:
df_raw_test_1.describe()

,1,Unnamed: 1,Unnamed: 2,2,Unnamed: 4,Unnamed: 5,3,Unnamed: 7,Unnamed: 8,4,...,Unnamed: 89,31,Unnamed: 91,Unnamed: 92,32,Unnamed: 94,Unnamed: 95,33,Unnamed: 97,Unnamed: 98
count,17524,17524,17524,25895,25895,25895,11749,11749,11749,20850,...,22968,22411,22411,22411,19084,19084,19084,12424,12424,12424
unique,17524,10522,17524,25895,15557,25895,11749,8504,11749,20850,...,22968,22411,12334,22411,19084,12997,19084,12424,9960,12424
top,Time,"152,7055",Stroke,Time,"143,3849",Stroke,Time,"139,7149",Stroke,Time,...,Stroke,Time,"165,2384",Stroke,Time,"164,2068",Stroke,Time,"153,2062",Stroke
freq,1,29,1,1,41,1,1,15,1,1,...,1,1,26,1,1,20,1,1,11,1

In [4]:
df_raw_test_1.head()

,1,Unnamed: 1,Unnamed: 2,2,Unnamed: 4,Unnamed: 5,3,Unnamed: 7,Unnamed: 8,4,...,Unnamed: 89,31,Unnamed: 91,Unnamed: 92,32,Unnamed: 94,Unnamed: 95,33,Unnamed: 97,Unnamed: 98
0,Time,Force,Stroke,Time,Force,Stroke,Time,Force,Stroke,Time,...,Stroke,Time,Force,Stroke,Time,Force,Stroke,Time,Force,Stroke
1,sec,N,mm,sec,N,mm,sec,N,mm,sec,...,mm,sec,N,mm,sec,N,mm,sec,N,mm
2,0,"0,03655751","3,333333E-05",0,"0,7931392","3,333333E-05",0,"1,265208","3,333333E-05",0,...,"3,333333E-05",0,"0,8773804","3,333333E-05",0,"0,8058548",0,0,"1,16984","3,333333E-05"
3,"0,01","0,04132589","0,0001333333","0,01","0,7804235","0,0001666667","0,01","1,266797","0,0001333333","0,01",...,"0,0001333333","0,01","0,890096","0,0001333333","0,01","0,8010864","0,0001333333","0,01","1,185735","0,0001333333"
4,"0,02","0,03655751","0,0004666667","0,02","0,7677078","0,0006333333","0,02","1,257261","0,0005333333","0,02",...,"0,0005","0,02","0,9012222","0,0005","0,02","0,8042653","0,0005666667","0,02","1,196861","0,0005333333"

In [9]:
df_melted = df_raw_test_1[['1', 'Unnamed: 1', 'Unnamed: 2']].melt(var_name='original_column', value_name='value')

In [10]:
df_melted.head(10)

  original_column value
0               1  Time
1               1   sec
2               1     0
3               1  0,01
4               1  0,02
5               1  0,03
6               1  0,04
7               1  0,05
8               1  0,06
9               1  0,07